---
abstract: 'access to hostip.info API'
author:
  - 'Makamaka Hannyaharamitu (makamaka[at]cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-HostipInfo
no_index:
  directory:
    - t
    - inc
requires:
  LWP: 0
  Test::More: 0
resources:
  repository: http://github.com/makamaka/WWW-HostipInfo
version: ''
